- alt: 产品图片 1
  description: 这是第 1 个产品
  image: /images/p-01.jpg
  name: 产品1
- alt: 产品图片 2
  description: 这是第 2 个产品
  image: /images/p-02.jpg
  name: 产品2
- alt: 产品图片 3
  description: 这是第 3 个产品
  image: /images/p-03.jpg
  name: 产品3
- alt: 产品图片 4
  description: 这是第 4 个产品
  image: /images/p-04.jpg
  name: 产品4
